habits/urls.py
# app urls
import habits_tracker.urls
import todolist.urls

from django.contrib import admin
# note imported as auth_views
from django.contrib.auth import views as auth_views
from django.urls import path, include

# note import as user_views
from users import views as user_views

from rest_framework import routers
from users.views import UserViewSet, GroupViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile', user_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    # path('', include('habits_tracker.urls')),
    # path('', include('todolist.urls')),

]

urlpatterns += [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

habits_tracker/urls.py
from django.urls import path
from habits_tracker import views

from .views import (GoalCreateView, GoalListView,
                    GoalUpdateView, GoalDeleteView,
                    GoalDetailView)


app_name = "habits"
urlpatterns = [
    path('', views.Home, name='homepage'),
    path('goal/add/', GoalCreateView.as_view(), name='goal_create'),
    path('goal/list/', GoalListView.as_view(), name='goal_list'),
    path('goal/<int:pk>/update', GoalUpdateView.as_view(), name='goal_update'),
    path('goal/<int:pk>/', GoalDetailView.as_view(), name='goal_detail'),
    path('goal/<int:pk>/delete', GoalDeleteView.as_view(), name='goal_delete'),
]

todolist/urls.py
from django.urls import path

from todolist.views import (
    TDL_CreateView, TDLItemsListView,
    TDL_DeleteView, TDL_ListView,
    TDL_UpdateView, TDLItems_CreateView,
    TDLItems_DeleteView, TDLItem_UpdateView)


app_name = 'tdl'
urlpatterns = [
    # Path for Todolists
    path('tdl/', TDL_ListView.as_view(), name='tdl_list'),
    path('tdl/add/', TDL_CreateView.as_view(), name='tdl_create'),
    path('tdl/<int:pk>/update/', TDL_UpdateView.as_view(), name='tdl_update'),
    path('tdl/<int:pk>/delete/', TDL_DeleteView.as_view(), name='tdl_delete'),
    path('tdl/<int:pk>/', TDLItemsListView.as_view(), name="tdl_detail"),
    # Path
    path('tdi/add/<int:pk>/', TDLItems_CreateView.as_view(), name='tdi_create'),
    path('tdi/<int:pk>/delete/', TDLItems_DeleteView.as_view(), name='tdi_delete'),
    path('tdi/<int:pk>/update/', TDLItem_UpdateView.as_view(), name='tdi_update'),
]

habits_tracker/models.py
import datetime as dt
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
# from django.db.models import Case, Value, When
from datetime import date, timedelta
from users.models import Profile
# Create your models here.


class Goal(models.Model):
    TS = 'To Start'
    PR = 'In Progress'
    AC = 'Achieved'
    GoalCheckBox = [
        (TS, 'To Start'),
        (PR, 'In Progress'),
        (AC, 'Achieved')
    ]
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    goal_title = models.CharField(max_length=25)
    goal_status = models.CharField(
        choices=GoalCheckBox,
        default=TS,
        max_length=11)
    mantra = models.TextField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.goal_title} {self.goal_status}"

    def get_absolute_url(self):
        return reverse("goal_detail", kwargs={"pk": self.pk})


class Habit(models.Model):
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    habit_title = models.CharField(max_length=40)
    notes = models.TextField(null=True, default='')

    def __str__(self):
        return f"{self.habit_title} to achieve {self.goal}, {self.goal.profile}"

    # class Habit(models.Model):
    #     goal = models.ForeignKey(
    #         Goal, on_delete=models.CASCADE,  primary_key=True)
    #     habit_title = models.CharField(
    #         max_length=40, unique=True)
    #     habit_desc = models.CharField(max_length=200)
    #     preparations = models.TextField(blank=True)
    #     commited = models.BooleanField(default=False)
    #     practised_today = models.DateField()

todolist/models.py
from django.db import models
from datetime import datetime, timedelta
from users.models import Profile
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import make_aware


def Tomorrow():
    settings.TIME_ZONE
    tmoz = datetime.today() + timedelta(days=1)
    tmoz = tmoz.replace(hour=18, minute=0, second=0, microsecond=0)
    tmoz = make_aware(tmoz)
    return tmoz


class TDlist(models.Model):
    title = models.CharField(max_length=25)
    completed = models.BooleanField(default=False)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"


class TDitem(models.Model):
    tdlist = models.ForeignKey(TDlist, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    duedate = models.DateTimeField(default=Tomorrow())
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.content} {self.duedate}, completed:{self.status}"

    def get_absolute_url(self):
        return reverse('tdl:tdl_detail', kwargs={'pk': self.tdlist.id})

    class Meta:
        ordering = ['duedate']


# class TDLsubtitle(models.Model):
#     item = models.ForeignKey(TDLitem, on_delete=models.CASCADE)
#     subtitle = models.CharField(max_length=100)
#     sub_status = models.BooleanField(default=False)

#     def __str__(self):
#         return self.subtitle


# class TDLnotes(models.Model):
#     item = models.ForeignKey(TDLitem, on_delete=models.CASCADE)
#     notes = models.TextField()

#     def __str__(self):
#         return self.notes

habits_tracker/forms.py
from django.forms import ModelForm
from django.forms import forms
from django.forms import modelformset_factory
from habits_tracker.models import *


class GoalForm(ModelForm):
    class Meta:
        model = Goal
        fields = ['goal_title', 'mantra']

todolist/forms.py
from django.forms import ModelForm
from django.forms import forms
from django.forms import modelformset_factory
from todolist.models import *


class TDListForm(ModelForm):

    class Meta:
        model = TDlist
        fields = ['title', 'completed']


class TDItemForm(ModelForm):

    class Meta:
        model = TDitem
        fields = ['tdlist', 'content', 'duedate', 'status']

habits_tracker/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Goal
from .forms import GoalForm
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
# Create your views here.


def Home(request):
    return render(request, 'habits/index.html')


class GoalListView(LoginRequiredMixin, ListView):
    template_name = "habits/goal_list.html"
    context_object_name = "goals"
    success_url = 'habits/goal_list.html'

    def get_queryset(self):
        qset = Goal.objects.filter(profile__id=self.request.user.id)
        return qset


class GoalCreateView(LoginRequiredMixin, CreateView):
    model = Goal
    fields = ['goal_title', 'mantra']
    template_name = "habits/goal_createform.html"
    success_url = reverse_lazy('habits:goal_list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class GoalDetailView(LoginRequiredMixin, DeleteView):
    model = Goal
    template_name = 'habits/goal_detail.html'
    context_object_name = 'goal'
    success_url = 'habits/goal_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["goal_detail"] = Goal.objects.all()
        return context


class GoalUpdateView(LoginRequiredMixin, UpdateView):
    model = Goal
    fields = ['goal_title', 'mantra']
    success_url = reverse_lazy('habits:goal_list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


# @require_http_methods(["POST"])
# def GoalUpdateView(request, goal_id):
#     to_update = get_object_or_404(Goal, pk=goal_id)
#     if request.user.profile == to_update.profile:


#     goal_title_to_update = User.Profile.goal_set.get(
#         pk=request.POST['goal_title'])
#     goal_mantra_to_update = User.Profile.goal_set.get(
#         pk=request.POST['mantra'])
#     to_update.goal_title = goal_title
#     selected_choice.save()
#     # Always return an HttpResponseRedirect after successfully dealing
#     # with POST data. This prevents data from being posted twice if a
#     # user hits the Back button.
#     return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

    # try:

    # except (KeyError, Goal.DoesNotExist):
    #     # Redisplay the question voting form.
    #     return render(request, 'goal/list.html', {
    #         'error_message': "You didn't select a choice.",
    #     })
    # else:


class GoalDeleteView(LoginRequiredMixin, DeleteView):
    model = Goal
    success_url = reverse_lazy('habits:goal_list')


# This view below is an example of how we can update the commited and practised fields in our model
# class AuthorDetailView(DetailView):

#     queryset = Author.objects.all()

#     def get_object(self):
#         obj = super().get_object()
#         # Record the last accessed date
#         obj.last_accessed = timezone.now()
#         obj.save()
#         return obj

todolist/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView, DetailView
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy, reverse, resolve
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TDlist, TDitem
from django.http import Http404

# Create your views here.


class TDL_ListView(LoginRequiredMixin, ListView):
    model = TDlist
    template_name = "todolist/tdl.html"
    context_object_name = 'lists'

    def get_queryset(self):
        ''' retrieves the queryset for that user '''
        user = self.request.user
        all_lists = TDlist.objects.all()
        return all_lists.filter(profile=user.profile)


class TDLItemsListView(ListView):
    template_name = 'todolist/tdl_detail.html'
    model = TDlist
    context_object_name = 'item'

    def get_queryset(self):
        list_in_focus = TDlist.objects.get(pk=self.kwargs['pk'])
        list_to_return = list_in_focus.tditem_set.all()
        return list_to_return

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        list_in_focus = TDlist.objects.get(pk=self.kwargs['pk'])
        context['list_in_focus'] = list_in_focus
        return context


class TDL_CreateView(LoginRequiredMixin, CreateView):
    model = TDlist
    fields = ['title', 'completed']
    template_name = "todolist/tdl.html"
    success_url = reverse_lazy('tdl:tdl_list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class TDL_UpdateView(LoginRequiredMixin, UpdateView):
    model = TDlist
    fields = ['title', 'completed']
    success_url = reverse_lazy('tdl:tdl_list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class TDL_DeleteView(LoginRequiredMixin, DeleteView):
    model = TDlist
    success_url = reverse_lazy('tdl:tdl_list')


# ***** ToDoItems  **********
class TDItem_ListView(LoginRequiredMixin, ListView):
    model = TDitem
    template_name = 'todolist/tditem_list.html'

    def get_context_data(self, **kwargs):
        list_in_focus = self.kwargs['pk']
        list_items = TDitem.objects.filter(tdlist=list_in_focus)
        return {'items': list_items, 'list_in_focus': list_in_focus}


class TDLItems_CreateView(LoginRequiredMixin, CreateView):
    model = TDitem
    fields = ['tdlist', 'content', 'duedate']
    template_name = 'todolist/tdl_detail.html'

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class TDLItems_DeleteView(LoginRequiredMixin, DeleteView):
    model = TDitem
    success_url = "/tdl/{tdlist_id}/"


class TDLItem_UpdateView(LoginRequiredMixin, UpdateView):
    model = TDitem
    fields = ['content', 'duedate']
    success_url = '/tdl/{tdlist_id}/'
    template_name = "todolist/tdl_detail.html"

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)

habits_tracker/templates/habits/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        Home
        {% endblock %}
    </title>
    {% load django_simple_bulma %}
    {% bulma %}
    {% font_awesome %}
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
</head>
<!-- Navigation block -->

{% block nav %}
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'habits:homepage' %}">
            <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
            <h1 class="title"> 📋 Habby ⏳ </h1>
        </a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
            data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'habits:homepage' %}" class="navbar-item">
                {% if user.is_authenticated %}
                Dashboard
                {% else %}
                Home
                {% endif %}
            </a>
            <a href="{% url 'habits:goal_list' %}" class="navbar-item">
                Habit tracker
            </a>
            <a href="{%  url 'tdl:tdl_list' %}" class="navbar-item">
                To Do List
            </a>
            <div class="navbar-item has-dropdown" id='menudropdown'>
                <a class="navbar-link">
                    More
                </a>
                <div class="navbar-dropdown " id='navdropdown'>
                    <a class="navbar-item">
                        Motivation
                    </a>
                    <a class="navbar-item">
                        Pomodoro Technique & Timer
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>
        {% if user.is_authenticated %}
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a href="{% url 'profile' %}" class="button is-outlined">
                        <strong>Profile</strong>
                    </a>
                    <a href="{% url 'logout' %}" class="button is-link">
                        Logout
                    </a>
                </div>
            </div>
        </div>
        {% else %}
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a href="{% url 'register' %}" class="button is-primary">
                        <strong>Sign up</strong>
                    </a>
                    <a href="{% url 'login' %}" class="button is-light">
                        Log in
                    </a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>


</nav>
{% endblock nav%}
<!-- End Navigation -->
<!-- Messages/Alerts block  -->
{% block messages %}
{% if messages %}
{% for message in messages %}
<article class="message">
    <div class="message-header">
        <p> Messages </p>
        <button class="delete" aria-label="delete"></button>
    </div>
    <div class="message-body">
        {{message}}
    </div>
</article>
{% endfor %}
{% endif %}
{% endblock messages %}
<!-- End Messages/Alerts -->

<body>
    <section class="hero is-fullheight" style="background-color: whitesmoke;">
        {% block content %}
        {% endblock content %}
        <!-- Sctn1 block  -->

        {% block sctn1 %}
        {%endblock sctn1%}
        <!-- End Sctn1 block -->
        {%block forms %}
        {%endblock forms%}

        {% block footer%}
        <!-- Footer -->
        <footer class=" footer">
            <div class="content has-text-centered">
                <p>
                    <strong>Habby the habit tracker</strong> by <a href="https://github.com/Pedro-D13/">Pedro Dias</a>.
                    The source
                    code is licensed
                    <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
                    is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"> {% lorem 5 w random %}</a>.
                </p>
            </div>
        </footer>
        <!-- End Footer -->
        {% endblock %}
        <script src="{% static 'habits/js/ageindays.js' %}" defer></script>
        <script src="{% static 'habits/js/navbar.js' %}" defer></script>
        <script src="{% static 'habits/js/onClickUpdate.js' %}" defer></script>
        <script src="{% static 'habits/js/dropdown.js' %}" defer></script>
        <script src="{% static 'habits/js/addtask.js' %}" defer></script>
        <script src="{% static 'habits/js/list_title.js' %}" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <!-- <script src="{% static 'habits/js/notification_delete.js' %}" defer></script> -->
    </section>
</body>

</html>

habits_tracker/templates/habits/goal_createform.html
{% extends "habits/base.html" %}


{% block forms %}
<div class="container is-centered">
    <form method="POST">
        {% csrf_token %}
        <label for="id_goal_title">Goal title:</label>
        <div class="control">
            <input type="text" name="goal_title" maxlength="25" required id="id_goal_title">
        </div>
        <label for="id_mantra">Mantra:</label>
        <div class="control">
            <textarea class="textarea" placeholder="A word or sound repeated to aid concentration in meditation."
                name="mantra" cols="" rows="" required id="id_mantra">
                    </textarea>
        </div>
        <div class="control">
            <button class="button is-link" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock forms %}

habits_tracker/templates/habits/goal_detail.html
{% extends 'habits/base.html' %}

{% block content %}

<div class="container">
    <div class="container">
        <h1> update this goal </h1>
    </div>
    <a class="button" href="{% url 'habits:goal_update' goal.id %}"> Update Goal</a>
</div>
{% endblock%}

habits_tracker/templates/habits/goal_list.html
{% extends 'habits/base.html' %}

{% block title %}
Goal list
{% endblock title%}

{% block sctn1 %}

<div class="container">
    <div class="Hero is-fluid">
        <div class="hero-body">
            <!-- Habits Column -->
            <div class="box">
                <small class="is-2"> Goals: {{user.profile.goal_set.count}}</small>
                <br>
                <small class="is-2"> Completed goals</small>
                {% for goal in goals %}
                <div class="notification is-success">
                    <form class="container" action="/goal/{{goal.id}}/delete" method="POST">
                        {% csrf_token %}
                        <div class="is-success has-icons-left">
                            <a class="icon is-left has-text-info" style="text-decoration: none;"
                                onclick="editgoaljs( {{goal.id}} )">
                                <i class="fas fa-pen"></i>
                            </a>
                            {{goal.goal_title | capfirst}} : {{goal.mantra |capfirst}}
                            <button class="delete is-danger" type="submit" value=""></button>
                        </div>
                    </form>
                    <form action="/goal/{{goal.id}}/update" class="is-hidden" id="goalupdate{{goal.id}}" method="post">
                        {% csrf_token %}
                        <div class="field">
                            <div class="control">
                                <input class="input" type="text" name="goal_title" required
                                    placeholder="edit: {{goal.goal_title | truncatechars:15 }}">
                            </div>
                        </div>
                        <div class="field">
                            <div class="control">
                                <input class="input" type="text" required name="mantra"
                                    placeholder="edit: {{goal.mantra | truncatechars:15 }}">
                            </div>
                        </div>
                        <button class="button is-info" type="submit" value="Update">Update</button>
                    </form>
                </div>
                {% empty %}
                <div class="container has-text-centered">
                    <button class="button is-white">
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span>
                            Add Goal
                        </span>
                    </button>
                </div>
                {% endfor %}
                <div class="box">
                    <form class="level" action="/goal/add/" method="POST">
                        {% csrf_token %}
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label" id="id_goal_title">Create a Goal</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <p class="control is-expanded">
                                        <input class="input" type="text" placeholder="Goal" name="goal_title"
                                            maxlength="25" required id="id_goal_title">
                                    </p>
                                </div>
                                <div class="field-label is-normal">
                                    <label class="label" for="id_mantra">Mantra</label>
                                </div>
                                <div class="field is-normal has-addons">
                                    <p class="control is-expanded">
                                        <input class="input" type="text" placeholder="Mantra" value="" name="mantra"
                                            required id="id_mantra">
                                    </p>
                                    <div class="control">
                                        <button class="button is-info" value="Create" type="submit">
                                            Submit
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock sctn1%}
<!-- <p class="panel-heading has-text-centered">
        </p>
        <p class="panel-tabs">
            <a class="is-active">All</a>
            <a>To Do Today</a>
            <a>This Week</a>
            <a>This Month</a>
        </p>
        <div class="panel-block">
            <p class="control has-icons-left">
                <input class="input is-link" type="text" placeholder="Search">
                <span class="icon is-left">
                    <i class="fas fa-search" aria-hidden="true"></i>
                </span>
            </p>
        </div> -->

habits_tracker/templates/habits/goal_update_form.html
{% extends "habits/base.html" %}

{% block forms %}
<div class="container is-centered">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button is-link" value="update" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock forms %}


<!-- <label for="id_goal_title">Goal title:</label>
<div class="control">
    <input type="text" name="goal_title" maxlength="25" required id="id_goal_title">
</div>
<label for="id_mantra">Mantra:</label>
<div class="control">
    <textarea class="textarea" placeholder="A word or sound repeated to aid concentration in meditation." name="mantra"
        cols="" rows="" required id="id_mantra">
                </textarea>
</div> -->

habits_tracker/templates/habits/index.html
{% extends 'habits/base.html'%}

{%block content %}

<!-- Hero Intro -->
<section class="hero">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Habby the habit Tracker
            </h1>
            <h2 class="subtitle">
                Track them to change them!
            </h2>
        </div>
    </div>
</section>
<!-- End intro -->
{% if user.is_authenticated %}
<section class="hero">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                DashBoard
            </h1>
        </div>
    </div>
</section>
{% else %}

<!-- Content section -->
<section class="hero is-medium is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title"> Did you know? </h1>
            <h2 class="subtitle">
                Maxwell Maltz, an American cosmetic surgeon and author of Psycho-Cybernetics, believed it took
                <strong>21 days</strong> to form a new
                habit, this is a common
                misconception as it takes little longer than that around 2 months. <br>Infact <strong> 66 days.
                </strong>
            </h2>
            <p class="is-medium"> the average human life span is <strong> 80 years </strong>, which
                equates to around
                <strong> 29220 days </strong>
                So in the grand Scheme of things you have ...
            </p>

            <div class="container">
                <p class="is-large has-text-centered " id="tochange"></p>
                <!-- Create a web component which asks the age and returns/ a calculation of the persons age -->
                <div class="buttons is-centered">
                    <button class="button is-rounded is-info is-centered" id="ageInputQ" onclick="ageInput()"> click to
                        check</button>
                    <a class="button is-link is-centered" href="{% url 'register' %}"> Join today </a>
                </div>
            </div>
        </div>
    </div>

    <div class="hero-foot">
        <nav class="tabs is-toggle is-toggle-rounded is-fullwidth">
            <div class="container">
                <ul>
                    <li class="is-active">
                        <a>Reasons to join</a>
                    </li>
                    <li>
                        <a>Motivation</a>
                    </li>
                    <li>
                        <a> Pomodoro Technique & Timer </a>
                    </li>
                </ul>
                <!-- all of these tabs below should be hidden until clicked -->
            </div>
        </nav>
        <div class="box is-hidden">
            <h2> “People think focus means saying yes to the thing you've got to focus on. But that's not what
                it means
                at all. It means
                saying no to the hundred other good ideas that there are.</h2><br>
            <p class=""> You have to pick carefully.
                <cite>
                    Steve jobs
                </cite>
            </p>

        </div>
    </div>
</section>
<!-- End of content -->

{% endif %}
{% endblock content %}

habits_tracker/templates/habits/personalpage.html
{% extends 'habits/base.html' %}

{% block sctn1 %}
<div class="columns">
    <div class="column">
        <div class="hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">
                        Goals
                    </h1>
                    <h2 class="subtitle">
                        track the goals you've set
                    </h2>
                    </h1>
                    {% for goal in goal_list %}
                    <li> {{ goal.user }} </li>
                    {% endfor %}
                </div>
                {{ user.username }}
            </div>
        </div>
    </div>
</div>
</section>
{%endblock sctn1%}

habits_tracker/templates/habits/todo_list.html
<!-- TO Do List -->
<div class="column is-one-third">
    <div class="box">
        <h3 class="title is-5 has-text-centered"> Add to List </h3>
        <form class="level" action="/goal/add/" method="POST">
            {% csrf_token %}
            <div class="level-left">
                <label for="id_goal_title">To Do List:</label>
                <input class="input is-rounded" type="text" name="goal_title" maxlength="25" required
                    id="id_goal_title">
            </div>
            <button class="button is-link" value="update" type="submit">Submit</button>
        </form>
    </div>
    <div class="content box">
        <h1 class="title is-4"> To-Dos </h1>
        {% for goal in goals %}
        <li> ----- </li>
        {% endfor %}
    </div>
    <!-- END To Do List -->
</div>