habits/urls.py
# app urls
import habits_tracker.urls
import todolist.urls

from django.contrib import admin
# note imported as auth_views
from django.contrib.auth import views as auth_views
from django.urls import path, include

# note import as user_views
from users import views as user_views

from rest_framework import routers
from users.views import UserViewSet, GroupViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile', user_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    # path('', include('habits_tracker.urls')),
    # path('', include('todolist.urls')),

]

urlpatterns += [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

todolist/urls.py
from django.urls import path

from todolist.views import (
    TDL_CreateView, TDLItemsListView,
    TDL_DeleteView, TDL_ListView,
    TDL_UpdateView, TDLItems_CreateView,
    TDLItems_DeleteView, TDLItem_UpdateView)


app_name = 'tdl'
urlpatterns = [
    # Path for Todolists
    path('tdl/', TDL_ListView.as_view(), name='tdl_list'),
    path('tdl/add/', TDL_CreateView.as_view(), name='tdl_create'),
    path('tdl/<int:pk>/update/', TDL_UpdateView.as_view(), name='tdl_update'),
    path('tdl/<int:pk>/delete/', TDL_DeleteView.as_view(), name='tdl_delete'),
    path('tdl/<int:pk>/', TDLItemsListView.as_view(), name="tdl_detail"),
    # Path
    path('tdi/add/<int:pk>/', TDLItems_CreateView.as_view(), name='tdi_create'),
    path('tdi/<int:pk>/delete/', TDLItems_DeleteView.as_view(), name='tdi_delete'),
    path('tdi/<int:pk>/update/', TDLItem_UpdateView.as_view(), name='tdi_update'),
]

todolist/models.py
from django.db import models
from datetime import datetime, timedelta
from users.models import Profile
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import make_aware


def Tomorrow():
    settings.TIME_ZONE
    tmoz = datetime.today() + timedelta(days=1)
    tmoz = tmoz.replace(hour=18, minute=0, second=0, microsecond=0)
    tmoz = make_aware(tmoz)
    return tmoz


class TDlist(models.Model):
    title = models.CharField(max_length=25)
    completed = models.BooleanField(default=False)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"


class TDitem(models.Model):
    tdlist = models.ForeignKey(TDlist, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    duedate = models.DateTimeField(default=Tomorrow())
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.content} {self.duedate}, completed:{self.status}"

    def get_absolute_url(self):
        return reverse('tdl:tdl_detail', kwargs={'pk': self.tdlist.id})

    class Meta:
        ordering = ['duedate']


# class TDLsubtitle(models.Model):
#     item = models.ForeignKey(TDLitem, on_delete=models.CASCADE)
#     subtitle = models.CharField(max_length=100)
#     sub_status = models.BooleanField(default=False)

#     def __str__(self):
#         return self.subtitle


# class TDLnotes(models.Model):
#     item = models.ForeignKey(TDLitem, on_delete=models.CASCADE)
#     notes = models.TextField()

#     def __str__(self):
#         return self.notes

todolist/forms.py
from django.forms import ModelForm
from django.forms import forms
from django.forms import modelformset_factory
from todolist.models import *


class TDListForm(ModelForm):

    class Meta:
        model = TDlist
        fields = ['title', 'completed']


class TDItemForm(ModelForm):

    class Meta:
        model = TDitem
        fields = ['tdlist', 'content', 'duedate', 'status']

todolist/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView, DetailView
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy, reverse, resolve
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TDlist, TDitem
from django.http import Http404

# Create your views here.


class TDL_ListView(LoginRequiredMixin, ListView):
    model = TDlist
    template_name = "todolist/tdl.html"
    context_object_name = 'lists'

    def get_queryset(self):
        ''' retrieves the queryset for that user '''
        user = self.request.user
        all_lists = TDlist.objects.all()
        return all_lists.filter(profile=user.profile)


class TDLItemsListView(ListView):
    template_name = 'todolist/tdl_detail.html'
    model = TDlist
    context_object_name = 'item'

    def get_queryset(self):
        list_in_focus = TDlist.objects.get(pk=self.kwargs['pk'])
        list_to_return = list_in_focus.tditem_set.all()
        return list_to_return

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        list_in_focus = TDlist.objects.get(pk=self.kwargs['pk'])
        context['list_in_focus'] = list_in_focus
        return context


class TDL_CreateView(LoginRequiredMixin, CreateView):
    model = TDlist
    fields = ['title', 'completed']
    template_name = "todolist/tdl.html"
    success_url = reverse_lazy('tdl:tdl_list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class TDL_UpdateView(LoginRequiredMixin, UpdateView):
    model = TDlist
    fields = ['title', 'completed']
    success_url = reverse_lazy('tdl:tdl_list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class TDL_DeleteView(LoginRequiredMixin, DeleteView):
    model = TDlist
    success_url = reverse_lazy('tdl:tdl_list')


# ***** ToDoItems  **********
class TDItem_ListView(LoginRequiredMixin, ListView):
    model = TDitem
    template_name = 'todolist/tditem_list.html'

    def get_context_data(self, **kwargs):
        list_in_focus = self.kwargs['pk']
        list_items = TDitem.objects.filter(tdlist=list_in_focus)
        return {'items': list_items, 'list_in_focus': list_in_focus}


class TDLItems_CreateView(LoginRequiredMixin, CreateView):
    model = TDitem
    fields = ['tdlist', 'content', 'duedate']
    template_name = 'todolist/tdl_detail.html'

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)


class TDLItems_DeleteView(LoginRequiredMixin, DeleteView):
    model = TDitem
    success_url = "/tdl/{tdlist_id}/"


class TDLItem_UpdateView(LoginRequiredMixin, UpdateView):
    model = TDitem
    fields = ['content', 'duedate']
    success_url = '/tdl/{tdlist_id}/'
    template_name = "todolist/tdl_detail.html"

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)

todolist/templates/todolist/tditem_list.html
{% extends 'habits/base.html'%}

{% block sctn1 %}
<div class="container">
    <div class="box">
        working {{list_in_focus}}
        <p>
            {% for item in items %}
            <li> {{item}} </li>
            <form class="button" action="/tdi/{{item.id}}/delete/{{list_in_focus}}/" method="POST">
                {% csrf_token %}
                <button type="submit" class="delete is-pulled-right"> delete </button>
            </form>
            {% empty %}
            you have nothing in this to do list
            {% endfor %}
        </p>
    </div>
    <form action="/tdi/add/" method="POST">
        {% csrf_token %}
        <div class="box">
            <select class="is-hidden" name="tdlist" required id="id_tdlist">
                <option value="{{list_in_focus}}"></option>
            </select>
            <label for="id_content">Content:</label>
            <input type="text" name="content" maxlength="50" required id="id_content">
            <label for="id_duedate">Duedate:</label></<label>
            <input type="text" name="duedate" value="2020-03-08 18:00:00" required id="id_duedate">
        </div>
        <button class="button" type="submit"> Submit </button>
    </form>
</div>

{% endblock %}

todolist/templates/todolist/tdl.html
{% extends 'habits/base.html' %}

{% block title %}
To Do List
{% endblock %}
{% block sctn1 %}
<!-- is-two-fifth-desktop is-hidden-tablet is-hidden-mobile -->
<section class="hero is-fullheight">
    <div class="columns">
        <div class="column is-one-fifth is-hidden-mobile">
            <article class="panel is-pulled-right">
                <p class="panel-heading" style=" border:none;">
                    Inbox
                </p>
                <a class="panel-block is-active" style="border: none;">
                    <span class="panel-icon">
                        <span class="mdi mdi-calendar"></span>
                    </span>
                    Today
                </a>
                <a class="panel-block" style="border: none;">
                    <span class="panel-icon">
                        <span class="mdi mdi-calendar-week"></span>
                    </span>
                    This Week
                </a>
                <a class="panel-block" id="projects-item" style="border: none;">
                    <span class="panel-icon">
                        <i class="fas fa-tasks"></i>
                    </span>
                    Projects
                    <span class="panel-icon is-small is-pulled-right">
                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                    </span>
                </a>
                <div class="dropdown has-text-centered" id="dropdown-menu-tdl">
                    <div class="dropdown-menu" role="menu">
                        {% for list in lists %}
                        <div class="dropdown-content">
                            <a class="link" id="project{{list}}" class="dropdown-item"
                                href="{% url 'tdl:tdl_detail' list.pk %}">
                                {{list}}
                            </a>
                        </div>
                        <hr class=" dropdown-divider">
                        {% empty %}
                        <div class="dropdown-content">
                            No Current Projects
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </article>
        </div>
        <div class="column is-three-fifths has-background-white"
            style="border:2px solid #a7a0a0; background-color: white; height:100vh;">
            <h2 class="title is-3" id="project-title"> Project Title
                <button class="button is-medium is-white is-pulled-right" id="addtaskbutton">
                    <span class="icon">
                        <i class="fas fa-plus"></i>
                        <span> Add </span>
                    </span>
                </button>
            </h2>
            <br>

            <form class="is-hidden" action="/tdl/add/" method="POST" id="addtaskinput">
                <div class="column">
                    {% csrf_token %}
                    <div class="field has-addons ">
                        <p class="control is-expanded">
                            <label class="is-hidden" for="id_title"></label>
                            <input class="input" type="text" placeholder="Task" name="title" maxlength="25" required
                                id="id_title">
                        </p>
                        <p class="control">
                            <a class="button">
                                Due Date:
                                <input type="date" placeholder="">

                            </a>
                        </p>
                    </div>
                    <div class="field is-grouped">
                        <p class="control">
                            <button class="button is-success" value="Create" type="submit"> Submit </button>
                        </p>
                        <p class=" control">
                            <button id='cancel' class="button is-danger">Cancel</button>
                        </p>
                    </div>
                </div>
            </form>
            {% for list in lists %}
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <a href="{% url 'tdl:tdl_detail' list.id %}">
                            {{list}}
                        </a>
                    </div>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            <a class="level-item">
                                <span class="icon is-small"><i class="far fa-edit"></i></span>
                            </a>
                        </div>
                    </nav>
                </div>
                <div class="media-right">
                    <form action="/tdl/{{list.pk}}/delete/" method="POST">
                        {% csrf_token %}
                        <button class="delete" type="submit">
                        </button>
                    </form>
                </div>
            </article>
            {% empty %}
            <h1> No lists created, Click "Add" Above to get started </h1>
            {% endfor %}
        </div>
    </div>

</section>


{% endblock sctn1 %}
{% block footer  %}
{% endblock footer %}




<!-- for loop to display the different project -->
<!-- 
{% for list in tdl %}
<div class="content">
    <ul style="list-style-type:none;">
        <li style="border-bottom: 2px solid #e9ddddce; padding-top:1rem;">
            <div class="control is-inline">
                <a class="checkbox">
                    <input type="checkbox" name="compeleted">
                    <span> {{list}} </span>
                </a>
            </div>
            <form class="is-inline-block is-pulled-right" action="/tdl/{{list.id}}/delete" method="POST"
                id="deleteform{{list.id}}">
                {% csrf_token %}
                <button onclick="document.getElementById('deleteform{{list.id}}').classList.toggle('is-hidden')"
                    type="submit" class="delete is-pulled-right"></button>
            </form>
        </li>
    </ul>
    {% endfor %} -->

todolist/templates/todolist/tdl_detail.html
{% extends 'habits/base.html' %}

{% block title %}
Current list:{{list_in_focus}}
{% endblock title %}

{% block sctn1 %}
<div class="container">
    <div class="box">

        <h2 class="title"> viewing {{list_in_focus}} list </h2>
        <ul>
            {% for each in item %}
            <li class="box">
                <form class="" action="/tdi/{{each.id}}/delete/" method="POST">
                    {% csrf_token %}
                    <button type="submit" value="Confirm" class="delete is-pulled-right"> delete </button>
                </form>
                <a class="icon has-text-info"
                    onclick="document.getElementById('add_{{each}}_form').classList.toggle('is-hidden')">
                    <span class="icon is-small"><i class="far fa-edit"></i></span>
                </a>
                {{each.content}}
                <div class="is-pulled right"> Due:{{each.duedate}} </div>
                <form action="/tdi/{{each.id}}/update/" class="is-hidden" id="add_{{each}}_form" method="post">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                            <input maxlength="50" id="id_content" class="input" type="text" name="content" required
                                placeholder="">
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <label for="id_duedate">Duedate:</label>
                            <input id="id_duedate" class="input" todayLabel='Today' type="date" name="duedate" required
                                value="{{each.duedate}}" placeholder="">
                        </div>
                    </div>
                    <button class="button is-info" type="submit" value="Update">Update</button>
                </form>
            </li>
            {% empty %}
            nothing to see here
            {% endfor %}
            <div class="box">
                <form action="/tdi/add/{{list_in_focus.id}}/" method="POST">
                    {% csrf_token %}
                    <tr>
                        <td><select class="is-hidden" name="tdlist" required id="id_tdlist">
                                <option value="{{list_in_focus.id}}"></option>
                            </select></td>
                    </tr>
                    <tr>
                        <th><label for="id_content">Content:</label></th>
                        <td><input type="text" name="content" required></td>
                    </tr>
                    <tr>
                        <th><label for="id_duedate">Duedate:</label></th>
                        <td><input type="text" name="duedate" value="2020-03-09 18:00:00" required id="id_duedate"></td>
                    </tr>
                    <button class="button" type="submit" value="save"> Submit </button>
                </form>
            </div>
        </ul>
    </div>
</div>


{% endblock sctn1 %}

todolist/templates/todolist/vue_page.html
{% extends 'habits/base.html' %}

{% block sctn1 %}

<div id="app">
    [[message]]
</div>

<script>
    var app = new Vue({
        delemiters: "[[]]",
        el: '#app',
        data: {
            message: 'Hello Vue!'
        }
    })

</script>
{% endblock sctn1 %}