habits/urls.py
# app urls
import habits_tracker.urls
import todolist.urls

from django.contrib import admin
# note imported as auth_views
from django.contrib.auth import views as auth_views
from django.urls import path, include

# note import as user_views
from users import views as user_views

from rest_framework import routers
from users.views import UserViewSet, GroupViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile', user_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    # path('', include('habits_tracker.urls')),
    # path('', include('todolist.urls')),

]

urlpatterns += [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

habits_tracker/urls.py
from django.urls import path
from habits_tracker import views

from .views import (GoalCreateView, GoalListView,
                    GoalUpdateView, GoalDeleteView,
                    GoalDetailView)


app_name = "habits"
urlpatterns = [
    path('', views.Home, name='homepage'),
    path('goal/add/', GoalCreateView.as_view(), name='goal_create'),
    path('goal/list/', GoalListView.as_view(), name='goal_list'),
    path('goal/<int:pk>/update', GoalUpdateView.as_view(), name='goal_update'),
    path('goal/<int:pk>/', GoalDetailView.as_view(), name='goal_detail'),
    path('goal/<int:pk>/delete', GoalDeleteView.as_view(), name='goal_delete'),
]

habits_tracker/models.py
import datetime as dt
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
# from django.db.models import Case, Value, When
from datetime import date, timedelta
from users.models import Profile
# Create your models here.


class Goal(models.Model):
    TS = 'To Start'
    PR = 'In Progress'
    AC = 'Achieved'
    GoalCheckBox = [
        (TS, 'To Start'),
        (PR, 'In Progress'),
        (AC, 'Achieved')
    ]
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    goal_title = models.CharField(max_length=25)
    goal_status = models.CharField(
        choices=GoalCheckBox,
        default=TS,
        max_length=11)
    mantra = models.TextField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.goal_title} {self.goal_status}"

    def get_absolute_url(self):
        return reverse("goal_detail", kwargs={"pk": self.pk})


class Habit(models.Model):
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    habit_title = models.CharField(max_length=40)
    notes = models.TextField(null=True, default='')

    def __str__(self):
        return f"{self.habit_title} to achieve {self.goal}, {self.goal.profile}"

    # class Habit(models.Model):
    #     goal = models.ForeignKey(
    #         Goal, on_delete=models.CASCADE,  primary_key=True)
    #     habit_title = models.CharField(
    #         max_length=40, unique=True)
    #     habit_desc = models.CharField(max_length=200)
    #     preparations = models.TextField(blank=True)
    #     commited = models.BooleanField(default=False)
    #     practised_today = models.DateField()

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    error_css_class = "error"
    required_css_class = 'required'

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', ]

users/views.py
#  non-restful imports
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegisterForm
from users.models import Profile


# Restful view imports
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from users.serializers import UserSerializer, GroupSerializer

# Create your views here.


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Your account has been created you are now able to login!')
            return redirect('login')
        else:
            messages.error(request, f'Account was not created try again')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    user_profile = Profile.objects.filter(user=request.user)
    return render(request, 'users/profile.html', {'user_person': user_profile})

#  Viewsets


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

users/templates/users/login.html
{% extends "habits/base.html" %}

{% block content %}
<div class="section">
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <div class="field">
                <label for="id_username" class="label">Username</label>
                <div class="control">
                    <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username"
                        maxlength="150" required id="id_username" class="input" placeholder="UrAwesome😎">
                </div>
            </div>
            <div class="field">
                <label class="label">Passsword</label>
                <div class="control">
                    <input type="password" name="password" autocomplete="current-password" required id="id_password"
                        class="input" placeholder="🙅‍♀nopassword123🙅‍♀">
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link" type="submit">Login</button>
                </div>
                <div class="control">
                    <a class="button is-link is-light" href="{% url 'register' %}">Need an account</a>
                </div>
            </div>
        </form>
        <div class="control">
            <a class="is-small is-muted is-link is-light" href="{% url 'password_reset' %}"> Forgot
                Password🤔</a>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'habits/base.html' %}

{% block content %}
<div class="hero">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h2> You have logged out </h2>
            <h1> I hope leaving isn't a new habit you're forming </h1>
            <div>
                <small> <a href="{% url 'login' %}"> Login again</a></small>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "habits/base.html" %}

{% block title %}
Password-Reset
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <div class="field">
                <h2 class="title"> Password Reset</h2>
                <label for="id_email">Email:</label>
                <div class="control">
                    <input class="input" type="email" name="email" autocomplete="email" maxlength="254" required
                        id="id_email">
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link" type="submit">Request Password Reset </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'habits/base.html' %}
{% block title %}
Password-Reset Complete
{% endblock %}

{% block content %}
<div class="section">
    <div class="notification is-primary">
        <button class="delete"></button>
        Your Passowrd has been set.
    </div>
    <a href="{% url 'login' %}" class="button is-info"> Sign In Here</a>
</div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "habits/base.html" %}


{% block title %}
Password-Reset
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <div class="field">
                <label class="label" for="id_new_password1">New password:</label>
                <div class="control">
                    <input class="input" type="password" name="new_password1" autocomplete="new-password" required
                        id="id_new_password1">
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_new_password2">New password confirmation:</label>
                <div class="control">
                    <input class="input" type="password" name="new_password2" autocomplete="new-password" required
                        id="id_new_password2">
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link" type="submit">Reset Password</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

<!-- <ul>
                    
                </ul>
                </span> -->

users/templates/users/password_reset_done.html
{% extends 'habits/base.html' %}
{% block title %}
Password-Reset confirmation
{% endblock %}



{% block content %}
<div class="section">
    <div class="notification is-primary">
        <button class="delete"></button>
        an email has been sent with instructions to reset your password.
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "habits/base.html" %}

{% block content %}
<div class="container has-text-centered">
    <h1 class="title is-primary"> {{ user.username }} </h1>
    {% if user.profile.goal_set.all == None  %}
    <h2 class=""> Click her to create some goals <a class="button" href="{% url 'goal_create'%}"> create </a></h2>
    {% else %}
    <div class="Hero is-fluid">
        <article class="panel is-link">
            <p class="panel-heading has-text-centered">
            </p>
            <p class="panel-tabs">
                <a class="is-active">All</a>
                <a>To Do Today</a>
                <a>This Week</a>
                <a>This Month</a>
            </p>
            <div class="panel-block">
                <p class="control has-icons-left">
                    <input class="input is-link" type="text" placeholder="Search">
                    <span class="icon is-left">
                        <i class="fas fa-search" aria-hidden="true"></i>
                    </span>
                </p>
            </div>
        </article>
        <div class="hero-body">
            <!-- Habits Column -->
            <div class="columns">
                <div class="column is-one-third">
                    <div class="title"><a href="{% url 'habits:goal_list'%}"> Habits </a></div>
                    <ol class="1 box">
                        {% for goal in user.profile.goal_set.all %}
                        <li> <a href="{% url 'habits:goal_update' goal.id %}"> {{goal.goal_title}} </a> </li>
                        {% endfor %}
                    </ol>
                </div>
                <!-- Habits Column -->
                <div class="column is-one-third">
                    <div class="title"> Status </div>
                    <ol class="1 box">
                        {% for goal in user.profile.goal_set.all %}
                        <li> {{goal.goal_status}} </li>
                        {% empty %}
                        <li> ----- </li>
                        {% endfor%}
                    </ol>
                </div>
                <!-- Habits Column -->
                <div class="column is-one-third">
                    <div class="title"><a href=""> To-Dos </a></div>
                    <ol class="1 box">
                        {% for goal in user.profile.goal_set.all %}
                        <li> ----- </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
    {% endif%}
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "habits/base.html" %}

{% block content %}
<div class="section">
    <div class="container">
        <h1> Register for an account below to begin tracking your habits </h1>
        <form method="POST">
            {% csrf_token %}
            <div class="field">
                <label for="{{form.username.id_for_label}}" class="label">Username</label>
                <div class="control">
                    <input name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus
                        required id="id_username" class="input is-info" type="text" placeholder="Text input">
                </div>
            </div>
            <div class="field">
                <label for="{{form.email.id_for_label}}" class="label">Email</label>
                <div class="control has-icons-left has-icons-right">
                    <input id="id_email" name="email" class="input is-info" type="email" required
                        placeholder="Email input">
                    <span class="icon is-small is-left">
                        <i class="fas fa-envelope"></i>
                    </span>
                    <span class="icon is-small is-right">
                        <i class="fas fa-exclamation-triangle"></i>
                    </span>
                </div>
                <!-- <p class="help is-danger">This email is invalid</p> -->
            </div>
            <div class="field">
                <label for="{{form.password1.id_for_label}}" class="label">Password</label>
                <div class="control has-icons-left has-icons-right">
                    <input name="password1" autocomplete="new-password" required id="id_password1"
                        class="input is-success" type="password" placeholder="First habbit, use password manager 😉"
                        value="">
                    <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                    </span>
                    <span class="icon is-small is-right">
                        <i class="fas fa-check"></i>
                    </span>
                </div>
                <div class="content">
                    <ol class="is-lower-alpha">
                        <li>Your password can’t be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can’t be a commonly used password.</li>
                        <li>Your password can’t be entirely numeric.</li>
                    </ol>
                </div>
                <!-- include a password check which checks to see if the password entered are the same probably in JS -->
                <!-- <p class="help is-success">Password is valid</p> -->
            </div>
            <div class="field">
                <label for="{{form.password2.id_for_label }}" class="label">Password</label>
                <div class="control has-icons-left has-icons-right">
                    <input name="password2" autocomplete="new-password" required id="id_password1"
                        class="input is-success" type="password" placeholder="" value="">
                    <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                    </span>
                    <span class="icon is-small is-right">
                        <i class="fas fa-check"></i>
                    </span>
                </div>
                <!-- <p class="help is-success">Password is valid</p> -->
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link" type="submit">Submit</button>
                </div>
                <div class="control">
                    <a class="button is-link is-light" href="{% url 'login' %}">Already have an account</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}